/*
 * (c) Francesco Capodanno 2015
 * Tutti i diritti sono riservati agli autori * 
 */
package com.francescoCapodannoIT.classes;


import java.awt.Component;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JSlider;

/**
 *
 * @author FrancescoCapodanno
 */
public class ResultsJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ResultsJFrame
     */
    Locale thisLocale;
    private String little_results_text;
    private String medium_results_text;
    private String expanse_results_text;
    private List<Integer> percentsBusyRooms;
    
    public ResultsJFrame() {
        
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//
    private void initComponents() {
        Translator.init_str_ResultsJFrame();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jToggleButton4 = new javax.swing.JToggleButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        DistributionPanel = new javax.swing.JPanel();
        jPanelMonitor1 = new PanelRoom();
        jPanelMonitor2 = new PanelRoom();
        jPanelMonitor3 = new PanelRoom();
        jPanelMonitor4 = new PanelRoom();
        jPanelMonitor5 = new PanelRoom();
        jPanelMonitor6 = new PanelRoom();
        jPanelMonitor7 = new PanelRoom();
        jPanelMonitor8 = new PanelRoom();
        jPanelMonitor9 = new PanelRoom();
        jPanelMonitor10 = new PanelRoom();
        jPanelMonitor11 = new PanelRoom();
        jPanelMonitor12 = new PanelRoom();
        jPanelMonitor13 = new PanelRoom();
        jPanelMonitor14 = new PanelRoom();
        jPanelMonitor15 = new PanelRoom();
        jPanelMonitor16 = new PanelRoom();
        labelRoom1 = new javax.swing.JLabel();
        labelRoom2 = new javax.swing.JLabel();
        labelRoom3 = new javax.swing.JLabel();
        labelRoom4 = new javax.swing.JLabel();
        labelRoom5 = new javax.swing.JLabel();
        labelRoom6 = new javax.swing.JLabel();
        labelRoom7 = new javax.swing.JLabel();
        labelRoom8 = new javax.swing.JLabel();
        labelRoom9 = new javax.swing.JLabel();
        labelRoom10 = new javax.swing.JLabel();
        labelRoom11 = new javax.swing.JLabel();
        labelRoom12 = new javax.swing.JLabel();
        labelRoom13 = new javax.swing.JLabel();
        labelRoom14 = new javax.swing.JLabel();
        labelRoom15 = new javax.swing.JLabel();
        labelRoom16 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        restRoomsLabel = new javax.swing.JLabel();
        emptyLabel = new javax.swing.JLabel();
        fullLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Results");
        setName("resultsFrame1"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(151, 152, 246));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 500));

        jTabbedPane1.setBackground(new java.awt.Color(151, 152, 246));
        jTabbedPane1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(540, 500));
        jTabbedPane1.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(151, 152, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 520));

        jScrollPane4.setBackground(new java.awt.Color(151, 152, 246));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(223, 48, 48)));
        jScrollPane4.setViewportView(jTextArea3);

        jToggleButton4.setBackground(new java.awt.Color(153, 153, 255));
        jToggleButton4.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(11, 146, 228));
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clipboard.png"))); // NOI18N
        jToggleButton4.setActionCommand("copyToClipBoard");
        jToggleButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(74, 207, 51), java.awt.Color.green, null, new java.awt.Color(32, 242, 56)));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jSlider1.setMinorTickSpacing(50);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(0);
        jSlider1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel1.setText(Translator.str_ResultsJFrame("meno dati"));

        jLabel2.setText(Translator.str_ResultsJFrame("più dati"));

        jToggleButton1.setText("+");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("-");
        jToggleButton3.setActionCommand("minus_slider");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButton4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton3)
                            .addComponent(jToggleButton1))
                        .addGap(25, 25, 25)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(Translator.str_ResultsJFrame("Riassunto"), jPanel1);

        jPanel3.setBackground(new java.awt.Color(151, 152, 246));

        jScrollPane2.setBackground(new java.awt.Color(151, 152, 246));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(223, 48, 48)));
        jScrollPane2.setViewportView(jTextArea2);

        jToggleButton2.setBackground(new java.awt.Color(153, 153, 255));
        jToggleButton2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(11, 146, 228));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clipboard.png"))); // NOI18N
        jToggleButton2.setActionCommand("copyToClipBoard");
        jToggleButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(74, 207, 51), java.awt.Color.green, null, new java.awt.Color(32, 242, 56)));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jToggleButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(Translator.str_ResultsJFrame("Riassunto per Aule"), jPanel3);

        jPanel4.setBackground(new java.awt.Color(151, 152, 246));

        DistributionPanel.setBackground(new java.awt.Color(0, 0, 51));
        DistributionPanel.setName("DistributionPanel"); // NOI18N

        javax.swing.GroupLayout jPanelMonitor1Layout = new javax.swing.GroupLayout(jPanelMonitor1);
        jPanelMonitor1.setLayout(jPanelMonitor1Layout);
        jPanelMonitor1Layout.setHorizontalGroup(
            jPanelMonitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor1Layout.setVerticalGroup(
            jPanelMonitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMonitor2Layout = new javax.swing.GroupLayout(jPanelMonitor2);
        jPanelMonitor2.setLayout(jPanelMonitor2Layout);
        jPanelMonitor2Layout.setHorizontalGroup(
            jPanelMonitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor2Layout.setVerticalGroup(
            jPanelMonitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor3.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor3Layout = new javax.swing.GroupLayout(jPanelMonitor3);
        jPanelMonitor3.setLayout(jPanelMonitor3Layout);
        jPanelMonitor3Layout.setHorizontalGroup(
            jPanelMonitor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor3Layout.setVerticalGroup(
            jPanelMonitor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor4.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor4Layout = new javax.swing.GroupLayout(jPanelMonitor4);
        jPanelMonitor4.setLayout(jPanelMonitor4Layout);
        jPanelMonitor4Layout.setHorizontalGroup(
            jPanelMonitor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor4Layout.setVerticalGroup(
            jPanelMonitor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor5.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor5Layout = new javax.swing.GroupLayout(jPanelMonitor5);
        jPanelMonitor5.setLayout(jPanelMonitor5Layout);
        jPanelMonitor5Layout.setHorizontalGroup(
            jPanelMonitor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor5Layout.setVerticalGroup(
            jPanelMonitor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor6.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor6Layout = new javax.swing.GroupLayout(jPanelMonitor6);
        jPanelMonitor6.setLayout(jPanelMonitor6Layout);
        jPanelMonitor6Layout.setHorizontalGroup(
            jPanelMonitor6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor6Layout.setVerticalGroup(
            jPanelMonitor6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor7.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor7Layout = new javax.swing.GroupLayout(jPanelMonitor7);
        jPanelMonitor7.setLayout(jPanelMonitor7Layout);
        jPanelMonitor7Layout.setHorizontalGroup(
            jPanelMonitor7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor7Layout.setVerticalGroup(
            jPanelMonitor7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor8.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor8Layout = new javax.swing.GroupLayout(jPanelMonitor8);
        jPanelMonitor8.setLayout(jPanelMonitor8Layout);
        jPanelMonitor8Layout.setHorizontalGroup(
            jPanelMonitor8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor8Layout.setVerticalGroup(
            jPanelMonitor8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor9.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor9Layout = new javax.swing.GroupLayout(jPanelMonitor9);
        jPanelMonitor9.setLayout(jPanelMonitor9Layout);
        jPanelMonitor9Layout.setHorizontalGroup(
            jPanelMonitor9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor9Layout.setVerticalGroup(
            jPanelMonitor9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor10.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor10Layout = new javax.swing.GroupLayout(jPanelMonitor10);
        jPanelMonitor10.setLayout(jPanelMonitor10Layout);
        jPanelMonitor10Layout.setHorizontalGroup(
            jPanelMonitor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor10Layout.setVerticalGroup(
            jPanelMonitor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor11.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor11Layout = new javax.swing.GroupLayout(jPanelMonitor11);
        jPanelMonitor11.setLayout(jPanelMonitor11Layout);
        jPanelMonitor11Layout.setHorizontalGroup(
            jPanelMonitor11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor11Layout.setVerticalGroup(
            jPanelMonitor11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor12.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor12Layout = new javax.swing.GroupLayout(jPanelMonitor12);
        jPanelMonitor12.setLayout(jPanelMonitor12Layout);
        jPanelMonitor12Layout.setHorizontalGroup(
            jPanelMonitor12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelMonitor12Layout.setVerticalGroup(
            jPanelMonitor12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor13.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor13Layout = new javax.swing.GroupLayout(jPanelMonitor13);
        jPanelMonitor13.setLayout(jPanelMonitor13Layout);
        jPanelMonitor13Layout.setHorizontalGroup(
            jPanelMonitor13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor13Layout.setVerticalGroup(
            jPanelMonitor13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor14.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor14Layout = new javax.swing.GroupLayout(jPanelMonitor14);
        jPanelMonitor14.setLayout(jPanelMonitor14Layout);
        jPanelMonitor14Layout.setHorizontalGroup(
            jPanelMonitor14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor14Layout.setVerticalGroup(
            jPanelMonitor14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor15.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor15Layout = new javax.swing.GroupLayout(jPanelMonitor15);
        jPanelMonitor15.setLayout(jPanelMonitor15Layout);
        jPanelMonitor15Layout.setHorizontalGroup(
            jPanelMonitor15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelMonitor15Layout.setVerticalGroup(
            jPanelMonitor15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMonitor16.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelMonitor16Layout = new javax.swing.GroupLayout(jPanelMonitor16);
        jPanelMonitor16.setLayout(jPanelMonitor16Layout);
        jPanelMonitor16Layout.setHorizontalGroup(
            jPanelMonitor16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelMonitor16Layout.setVerticalGroup(
            jPanelMonitor16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        labelRoom1.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom1.setText("1");
        labelRoom1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom2.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom2.setText("2");
        labelRoom2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom3.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom3.setText("3");
        labelRoom3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom4.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom4.setText("4");
        labelRoom4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom5.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom5.setText("5");
        labelRoom5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom6.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom6.setText("6");
        labelRoom6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom7.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom7.setText("7");
        labelRoom7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom8.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom8.setText("8");
        labelRoom8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom9.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom9.setText("9");
        labelRoom9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom10.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom10.setText("10");
        labelRoom10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom11.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom11.setText("11");
        labelRoom11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom12.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom12.setText("12");
        labelRoom12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom13.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom13.setText("13");
        labelRoom13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom14.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom14.setText("14");
        labelRoom14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom15.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom15.setText("15");
        labelRoom15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRoom16.setForeground(new java.awt.Color(255, 255, 0));
        labelRoom16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom16.setText("16");
        labelRoom16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        restRoomsLabel.setForeground(new java.awt.Color(255, 255, 0));
        restRoomsLabel.setText("restRoomsLabel");

        emptyLabel.setForeground(new java.awt.Color(153, 255, 51));
        emptyLabel.setText("emptyLabel");

        fullLabel.setForeground(new java.awt.Color(255, 0, 51));
        fullLabel.setText("fullLabel");

        javax.swing.GroupLayout DistributionPanelLayout = new javax.swing.GroupLayout(DistributionPanel);
        DistributionPanel.setLayout(DistributionPanelLayout);
        DistributionPanelLayout.setHorizontalGroup(
            DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DistributionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DistributionPanelLayout.createSequentialGroup()
                        .addComponent(labelRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRoom3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRoom4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRoom5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelRoom6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRoom7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelRoom8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(DistributionPanelLayout.createSequentialGroup()
                        .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DistributionPanelLayout.createSequentialGroup()
                                .addComponent(jPanelMonitor9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelMonitor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelMonitor11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelMonitor12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(DistributionPanelLayout.createSequentialGroup()
                                .addComponent(jPanelMonitor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelMonitor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelMonitor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelMonitor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DistributionPanelLayout.createSequentialGroup()
                                .addComponent(jPanelMonitor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jPanelMonitor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelMonitor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DistributionPanelLayout.createSequentialGroup()
                                .addComponent(jPanelMonitor13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelMonitor14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelMonitor15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelMonitor8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelMonitor16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))
                    .addGroup(DistributionPanelLayout.createSequentialGroup()
                        .addComponent(labelRoom9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRoom10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRoom11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelRoom12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRoom13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRoom14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelRoom15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(labelRoom16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DistributionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DistributionPanelLayout.createSequentialGroup()
                        .addComponent(emptyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fullLabel))
                    .addComponent(restRoomsLabel)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        DistributionPanelLayout.setVerticalGroup(
            DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DistributionPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRoom1)
                    .addComponent(labelRoom2)
                    .addComponent(labelRoom3)
                    .addComponent(labelRoom4)
                    .addComponent(labelRoom5)
                    .addComponent(labelRoom6)
                    .addComponent(labelRoom7)
                    .addComponent(labelRoom8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelMonitor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRoom9)
                        .addComponent(labelRoom10)
                        .addComponent(labelRoom11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRoom13)
                        .addComponent(labelRoom12)
                        .addComponent(labelRoom14)
                        .addComponent(labelRoom15)
                        .addComponent(labelRoom16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelMonitor9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMonitor16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(restRoomsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emptyLabel)
                    .addComponent(fullLabel))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 102));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("jLabel3");
        jLabel3.setOpaque(true);
        jScrollPane1.setViewportView(jLabel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DistributionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DistributionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(Translator.str_ResultsJFrame("Distribuzione"), jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("summary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
         toClipBoardSummary();
        Component fr = null;
         JOptionPane.showMessageDialog(fr,
            Translator.str_ResultsJFrame("Il seguente testo è copiato negli appunti") ,
            Translator.str_ResultsJFrame("Copia negli appunti"),
           JOptionPane.INFORMATION_MESSAGE);
         
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        toClipBoardRooms();
        Component fr = null;
         JOptionPane.showMessageDialog(fr,
            Translator.str_ResultsJFrame("Il seguente testo è copiato negli appunti") ,
            Translator.str_ResultsJFrame("Copia negli appunti"),
           JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        JSlider jslider = (JSlider) evt.getSource();
       
        if (jslider.getValue() == 50) {setResults(this.medium_results_text);}
        else if (jslider.getValue() == 100) {setResults(this.expanse_results_text);}
        else if (jslider.getValue() == 0) {setResults(this.little_results_text);}
        
// prendi il valore e fai
    }//GEN-LAST:event_jSlider1StateChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jSlider1.getValue() <=100)
        {
        jSlider1.setValue(jSlider1.getValue() + 50);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        if (jSlider1.getValue() > 0)
        {
        jSlider1.setValue(jSlider1.getValue() - 50);
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ResultsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//
    private javax.swing.JPanel DistributionPanel;
    private javax.swing.JLabel emptyLabel;
    private javax.swing.JLabel fullLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private PanelRoom jPanelMonitor1;
    private PanelRoom jPanelMonitor10;
    private PanelRoom jPanelMonitor11;
    private PanelRoom jPanelMonitor12;
    private PanelRoom jPanelMonitor13;
    private PanelRoom jPanelMonitor14;
    private PanelRoom jPanelMonitor15;
    private PanelRoom jPanelMonitor16;
    private PanelRoom jPanelMonitor2;
    private PanelRoom jPanelMonitor3;
    private PanelRoom jPanelMonitor4;
    private PanelRoom jPanelMonitor5;
    private PanelRoom jPanelMonitor6;
    private PanelRoom jPanelMonitor7;
    private PanelRoom jPanelMonitor8;
    private PanelRoom jPanelMonitor9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel labelRoom1;
    private javax.swing.JLabel labelRoom10;
    private javax.swing.JLabel labelRoom11;
    private javax.swing.JLabel labelRoom12;
    private javax.swing.JLabel labelRoom13;
    private javax.swing.JLabel labelRoom14;
    private javax.swing.JLabel labelRoom15;
    private javax.swing.JLabel labelRoom16;
    private javax.swing.JLabel labelRoom2;
    private javax.swing.JLabel labelRoom3;
    private javax.swing.JLabel labelRoom4;
    private javax.swing.JLabel labelRoom5;
    private javax.swing.JLabel labelRoom6;
    private javax.swing.JLabel labelRoom7;
    private javax.swing.JLabel labelRoom8;
    private javax.swing.JLabel labelRoom9;
    private javax.swing.JLabel restRoomsLabel;
    // End of variables declaration//

    void setResults(String toString) {
       jTextArea3.setText(toString);
       jTextArea3.setCaretPosition(0);
      
       
       //this.setBounds(600, 400, 600, 500);
    }
    
    void setResultsForRooms(String toString)
    {
        jTextArea2.setText(toString);
        jTextArea2.setCaretPosition(0);
        this.jLabel3.setText(Translator.str_ResultsJFrame("Distribuzione uso aule"));
    }
    
    void toClipBoardRooms()
    {
    StringSelection selection = new StringSelection(jTextArea2.getText());
    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    clipboard.setContents(selection, selection);
    }
    void toClipBoardSummary()
    {
    StringSelection selection = new StringSelection(jTextArea3.getText());
    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    clipboard.setContents(selection, selection);
    }

    void setMediumResults(String toString) {
        this.medium_results_text = toString;
     
    }

    void setExpanseResults(String toString) {
       this.expanse_results_text = toString;
    }
    
    void setLittleResults(String toString)
    {
        this.little_results_text = toString;
    }
    
    void setSlidertoStart()
    {
       jSlider1.setValue(0);
    }
    
    void setValuesRooms(List<Integer> values)
    {        
        this.emptyLabel.setText(Translator.str_ResultsJFrame("Vuoto"));
        this.fullLabel.setText(Translator.str_ResultsJFrame("Pieno"));
        this.restRoomsLabel.setText(Translator.str_ResultsJFrame("Resto delle aule"));
        //this.jPanelMonitor1.rooms = 1;
        
        jPanelMonitor1.setValue(0);
        jPanelMonitor2.setValue(0);
        jPanelMonitor3.setValue(0);
        jPanelMonitor4.setValue(0);
        jPanelMonitor5.setValue(0);
        jPanelMonitor6.setValue(0);
        jPanelMonitor7.setValue(0);
        jPanelMonitor8.setValue(0);
        jPanelMonitor9.setValue(0);
        jPanelMonitor10.setValue(0);
        jPanelMonitor11.setValue(0);
        jPanelMonitor12.setValue(0);
        jPanelMonitor13.setValue(0);
        jPanelMonitor14.setValue(0);
        jPanelMonitor15.setValue(0);
        jPanelMonitor16.setValue(0);
        
        
        
       
       
        int num_Aule = values.size();
        if (values.size() > 0)
        { 
           for (int i=0; i<values.size(); i++)
           {
           if (i == 0) {jPanelMonitor1.setValue(values.get(i));
                        //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                         
                          }
             else if (i == 1) {jPanelMonitor2.setValue(values.get(i));
                                //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                               }
             
             else if (i == 2){ jPanelMonitor3.setValue(values.get(i));
                                //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                               }
               
             else if (i == 3){jPanelMonitor4.setValue(values.get(i));
                               //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                              }
           
           else if (i == 4){jPanelMonitor5.setValue(values.get(i));
                               //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                              }
           
           else if (i == 5){jPanelMonitor6.setValue(values.get(i));
                              //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                          }
           
           else if (i == 6){jPanelMonitor7.setValue(values.get(i));
                               //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                             }
           
           else if (i == 7){jPanelMonitor8.setValue(values.get(i));
                               //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                              }
           
           else if (i == 8){jPanelMonitor9.setValue(values.get(i));
                               //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                           }
           
           else if (i == 9){jPanelMonitor10.setValue(values.get(i));
                               //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                             }
           else if (i == 10){jPanelMonitor11.setValue(values.get(i));
                              //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                                             
           }
           else if (i == 11){jPanelMonitor12.setValue(values.get(i));
                               //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                             
               
           }
           else if (i == 12){jPanelMonitor13.setValue(values.get(i));
                                 //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                             
               
           }
           else if (i == 13){jPanelMonitor14.setValue(values.get(i));
            //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                             
               
           }
           else if (i == 14){jPanelMonitor15.setValue(values.get(i));
                                //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                           
               
           }
           else if (i == 15){jPanelMonitor16.setValue(values.get(i));
            //System.out.println("L'aula " + (i +1) +" Occupata al:" + values.get(i)+"%");
                            
               
           }    
               
           }              
              
              
          
          
        }
        System.out.println(num_Aule);
       
       
        
        
        
        
        //percentsBusyRooms = values;
        repaint();
        validate();
       
    }
 
    /**
     * This class is for this static Frame. UpdateUI with the translated strings
     */
    public void updateTranslatedText()
    {
        this.emptyLabel.setText(Translator.str_ResultsJFrame("Vuoto"));
        this.fullLabel.setText(Translator.str_ResultsJFrame("Pieno"));
        this.restRoomsLabel.setText(Translator.str_ResultsJFrame("Resto delle aule"));
        this.jLabel3.setText(Translator.str_ResultsJFrame("Distribuzione uso aule"));
        this.jTabbedPane1.setTitleAt(0,Translator.str_ResultsJFrame("Riassunto"));
        this.jTabbedPane1.setTitleAt(1, Translator.str_ResultsJFrame("Riassunto per Aule"));
        this.jTabbedPane1.setTitleAt(2, Translator.str_ResultsJFrame("Distribuzione"));
        
        this.jPanel1.updateUI();
        this.jPanel2.updateUI();
        this.jPanel3.updateUI();
        this.jPanel4.updateUI();
        validate();
    }
}
